# Import firebase and random modules
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db
import random

# Initialize firebase with your config
cred = credentials.Certificate("sample-fd33f-firebase-adminsdk-bud5w-41a01b9c3e.json")
firebase_admin.initialize_app(cred, {
    "databaseURL": "https://sample-fd33f-default-rtdb.firebaseio.com"
})

# Create a database reference to your data
ref = db.reference("server/saving-data/fireblog")

# Create a child reference for users
users_ref = ref.child("users")

# Use push() to add a new node to the list of data and get the reference to the new data path
new_user_ref = users_ref.push()

# Use the key property to get the unique ID generated by push()
user_id = new_user_ref.key

# Use random.randint() to generate a random number between 1 and 100
random_number = random.randint(1, 100)

# Use set() to save a user object to the database with the user's ID, username, full name, and random number
new_user_ref.set({
    "user_id": user_id,
    "username": "user123",
    "full_name": "User One Two Three",
    "random_number": random_number
})
